config/routes.rb
Rails.application.routes.draw do
  resources :bids
  devise_for :users
  resources :items do
    collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
    end

  end

  root 'items#index'

  resources :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #post 'bind/index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize( user )
    user ||= User.new

    # Define User abilities
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end

  #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord

  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :bidding

end

app/models/item.rb
class Item < ApplicationRecord
  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  resourcify

  paginates_per 6
  has_many :bids
  accepts_nested_attributes_for :bids , :reject_if => :all_blank, :allow_destroy => true

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  mount_uploader :avatar, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bids


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end


   def current_item
    return unless [:item]
    @current_item ||= Item.find([:item_id])
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]


  def index
    @bids = Bid.all
  end
  def create
   @item = Item.find(bid_params[:item_id])
    @bid = @item.bids.build(user: current_user)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @item, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_bid
      @bid = Bid.find(params[:id])
    end


    def bid_params
      params.require(:bid).permit(:item_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]



  def index
    @q = Item.ransack(search_params)
    @items = @q.result(distinct: true).page params[:page]

    # @search = Item.search(params[:q])
    # @items = @search.result.page params[:page]
  end

  def play

  end


  def create
    @item = Item.new(item_params)


    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end



  def search_params
    params.permit(q: [ :name_cont ])["q"].to_h
  end

  def item_params
      params.require(:item).permit(:name, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/bids/_form.html.erb
<%= link_to "Bid It", bids_path(bid: { item_id: @item.id}), method: :post %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bids</h1>

<table>
  <thead>
    <tr>
      <th>Bidding</th>
      <th>User</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.bidding %></td>
        <td><%= bid.user_id %></td>
        <td><%= bid.item_id %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bidding:</strong>
  <%= @bid.bidding %>
</p>

<p>
  <strong>User:</strong>
  <%= @bid.user_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @bid.item_id %>
</p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

app/views/items/_form.html.erb
<%= form_for @item = Item.new, html: { multipart: true } do  |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<%= search_form_for @q do |f| %>
    <%= f.search_field :name_cont %>
    <%= f.submit  %>
<% end %>

<h1>Items</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= image_tag item.image.url(:medium) %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) if current_user and current_user.has_role? :admin %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: {confirm: 'Are you sure?'} if current_user and current_user.has_role? :admin %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= paginate @items %>
<%= link_to 'New Item', new_item_path if current_user and current_user.has_role? :admin %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>
<%= image_tag @item.image.url(:medium) %>

<%= render 'bids/form' %>
<%= link_to 'Edit', edit_item_path(@item) if current_user and current_user.has_role? :admin %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lottery</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<% if current_user %>
    <p>Welcome <%= current_user.email %></p>
    <%= link_to 'logout', destroy_user_session_path, method: :delete %>
    <%= link_to 'Edit profile', edit_user_registration_path %>
<% else %>
    <%= link_to 'Login', new_user_session_path %>
    <%= link_to 'Register', new_user_registration_path %>
<% end %>
<%= yield %>
</body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


</html>